name: 🌀 DevOps Update
description: Suggest a feature
title: "[DevOps Update]: "
body:
  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for this feature.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Please provide a detailed description of the update you are requesting.
      placeholder: Describe the new update or enhancement you'd like to see.
    validations:
      required: true


  - type: checkboxes
    id: terms
    attributes:
      label: Record
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
        - label: "I want to work on this issue"
          required: False
        - label: "I'm willing to provide further clarification or assistance if needed."
          required: False